header:
  license:
    spdx-id: BSD-3-Clause
    copyright-owner: Jupyter Development Team
    software-name: JupyterLab
    content: |
      Copyright (c) Jupyter Development Team.
      Distributed under the terms of the Modified BSD License.

  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/.*'
    - 'LICENSE'
    - tsconfig.tsbuildinfo
    - node_modules/**
    - node_modules/.**
    - 'yarn.lock'

  comment: on-failure
