/* -----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/
/*
 * Generated by scripts/update_yarn_version.py -- do not edit the literals by
 * hand. After replacing jupyter_builder/yarn.js, run that script and commit the
 * result; it keeps these values in sync with jupyter_builder/_yarn_info.py.
 */

/**
 * Version of the Yarn CLI bundle vendored as `jupyter_builder/yarn.js`.
 */
export const YARN_VERSION = '3.5.0';

/**
 * SHA-256 hex digest of the vendored Yarn CLI bundle.
 */
export const YARN_SHA256 =
  'f1e8c736b71a42f526edfe78b8c82a22c142f8e6b853ab1c987a0bbd891efdce';

/**
 * Value to put in the `packageManager` field of a `package.json`.
 */
export const YARN_PACKAGE_MANAGER = `yarn@${YARN_VERSION}`;
