# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

"""Version and integrity constants for the vendored ``yarn.js``.

Generated by ``scripts/update_yarn_version.py``. Do not edit the literals by
hand. After replacing ``jupyter_builder/yarn.js``, run that script and commit
the result; ``--check`` reports drift.
"""

from __future__ import annotations

from pathlib import Path

#: Version of the vendored Yarn CLI bundle.
YARN_VERSION: str = "3.5.0"

#: SHA-256 hex digest of the vendored Yarn CLI bundle.
YARN_SHA256: str = "f1e8c736b71a42f526edfe78b8c82a22c142f8e6b853ab1c987a0bbd891efdce"

#: Value to put in the ``packageManager`` field of a ``package.json``.
YARN_PACKAGE_MANAGER: str = f"yarn@{YARN_VERSION}"

#: Location of the vendored bundle, for tools that need to inspect or run it.
YARN_PATH: Path = Path(__file__).resolve().parent / "yarn.js"
